### ISSUE TITLE
[bug] object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by mzemb** [aacebedo/machination#47]
machination create --sharedfolder /home/titi/toto /mnt/project --sharedfolder /home/titi/tutu /mnt/install --no-interactive --verbose <template>:1.0 <instName>
[...]
Templates loaded.
Instances loaded.
Instance <instName> does not exist, proceeding to its creation.
[...]
Unable to create machine instance <instName>: object of type 'NoneType' has no len().
Traceback (most recent call last):
  File "/usr/local/share/machination/python/machination/cmdline.py", line 454, in createMachineInstance
    (template, arch, osversion, provider, provisioner, guestInterfaces, sharedFolders) = w.execute(args,templates)
  File "/usr/local/share/machination/python/machination/cmdline.py", line 249, in execute
    if(len(args.guestinterface) < template.getGuestInterfaces()):
TypeError: object of type 'NoneType' has no len()

**Comment by mzemb** [comment]
patch: line 249 of cmdLine.py :
"+ args.guestinterface!=None and "
